### ISSUE TITLE
fulltext.encode('latin-1') in libzotero gracefully crashes without notification from command line

### ISSUE THREAD

**Issue by punassuming** [smathot/Gnotero#4]
if conducting a zotero.search() from the command line, I have noticed that the attachment_query fetchall() will stop iterating after it comes across any unicode characters in the attachment filename.  I have avoided this for the time being by commenting out
# att = item[1].encode("latin-1")

to 
att = item[1]
on line 227

If I don't do this, all item.fulltext after the first unicode filename is found are set as 'None'

I think it might be from the os.join command later on, as all the individual segments need to be the same encoding, but I can't be sure at this point.

**Comment by smathot** [comment]
Thanks! I'll look into it.
